In [2]:
import pandas as pd
df=pd.read_csv("global air pollution dataset.csv")
df=pd.DataFrame(df)
new_df=pd.DataFrame(df)
df.head()

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good

In [3]:
df.tail()

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
23458,India,Gursahaiganj,184,Unhealthy,3,Good,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,Good,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,Good,38,Good,0,Good,70,Moderate

In [4]:
df.shape

(23463, 12)

In [5]:
df.describe()

,AQI Value,CO AQI Value,Ozone AQI Value,NO2 AQI Value,PM2.5 AQI Value
count,23463.000000,23463.000000,23463.000000,23463.000000,23463.000000
mean,72.010868,1.368367,35.193709,3.063334,68.519755
std,56.055220,1.832064,28.098723,5.254108,54.796443
min,6.000000,0.000000,0.000000,0.000000,0.000000
25%,39.000000,1.000000,21.000000,0.000000,35.000000
50%,55.000000,1.000000,31.000000,1.000000,54.000000
75%,79.000000,1.000000,40.000000,4.000000,79.000000
max,500.000000,133.000000,235.000000,91.000000,500.000000

In [6]:
df.value_counts()

Country      City         AQI Value  AQI Category                    CO AQI Value  CO AQI Category  Ozone AQI Value  Ozone AQI Category  NO2 AQI Value  NO2 AQI Category  PM2.5 AQI Value  PM2.5 AQI Category
Zimbabwe     Zvishavane   39         Good                            1             Good             18               Good                0              Good              39               Good                              1
Afghanistan  Acin         62         Moderate                        0             Good             46               Good                0              Good              62               Moderate                          1
             Anar Darreh  126        Unhealthy for Sensitive Groups  1             Good             42               Good                0              Good              126              Unhealthy for Sensitive Groups    1
             Andarab      104        Unhealthy for Sensitive Groups  0             Good             34               Good                0              Good              104              Unhealthy for Sensitive Groups    1
             Asadabad     131        Unhealthy for Sensitive Groups  1             Good             43               Good                0              Good              131              Unhealthy for Sensitive Groups    1
                                                                                                                                                                                                                            ..
             Eskasem      85         Moderate                        0             Good             14               Good                0              Good              85               Moderate                          1
             Deh Rawud    49         Good                            0             Good             49               Good                0              Good              47               Good                              1
             Dawlatabad   92         Moderate                        1             Good             43               Good                0              Good              92               Moderate                          1
             Ciras        90         Moderate                        0             Good             26               Good                0              Good              90               Moderate                          1
             Carikar      67         Moderate                        0             Good             37               Good                0              Good              67               Moderate                          1
Name: count, Length: 23035, dtype: int64

In [7]:
df.columns

Index(['Country', 'City', 'AQI Value', 'AQI Category', 'CO AQI Value',
       'CO AQI Category', 'Ozone AQI Value', 'Ozone AQI Category',
       'NO2 AQI Value', 'NO2 AQI Category', 'PM2.5 AQI Value',
       'PM2.5 AQI Category'],
      dtype='object')

In [8]:
df.info

<bound method DataFrame.info of                         Country              City  AQI Value AQI Category  \
0            Russian Federation        Praskoveya         51     Moderate
1                        Brazil  Presidente Dutra         41         Good
2                         Italy   Priolo Gargallo         66     Moderate
3                        Poland         Przasnysz         34         Good
4                        France          Punaauia         22         Good
...                         ...               ...        ...          ...
23458                     India      Gursahaiganj        184    Unhealthy
23459                    France            Sceaux         50         Good
23460                     India          Mormugao         50         Good
23461  United States of America       Westerville         71     Moderate
23462                  Malaysia            Marang         70     Moderate

       CO AQI Value CO AQI Category  Ozone AQI Value Ozone AQI Category  \
0                 1            Good               36               Good
1                 1            Good                5               Good
2                 1            Good               39               Good
3                 1            Good               34               Good
4                 0            Good               22               Good
...             ...             ...              ...                ...
23458             3            Good              154          Unhealthy
23459             1            Good               20               Good
23460             1            Good               22               Good
23461             1            Good               44               Good
23462             1            Good               38               Good

       NO2 AQI Value NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category
0                  0             Good               51           Moderate
1                  1             Good               41               Good
2                  2             Good               66           Moderate
3                  0             Good               20               Good
4                  0             Good                6               Good
...              ...              ...              ...                ...
23458              2             Good              184          Unhealthy
23459              5             Good               50               Good
23460              1             Good               50               Good
23461              2             Good               71           Moderate
23462              0             Good               70           Moderate

[23463 rows x 12 columns]>

In [9]:
df.isnull().sum()

Country               427
City                    1
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
dtype: int64

In [10]:
# data=df[["AQI Value","Ozone AQI Value"]]
# data.head()
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [11]:
df=df.dropna(subset=["Country"])
df.head()

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good

In [12]:
df.isnull().sum()

Country               0
City                  1
AQI Value             0
AQI Category          0
CO AQI Value          0
CO AQI Category       0
Ozone AQI Value       0
Ozone AQI Category    0
NO2 AQI Value         0
NO2 AQI Category      0
PM2.5 AQI Value       0
PM2.5 AQI Category    0
dtype: int64

In [13]:
new_df.isnull().sum()

Country               427
City                    1
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
dtype: int64

In [14]:
new_df.fillna("unknown")

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3,Good,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,Good,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,Good,38,Good,0,Good,70,Moderate

In [15]:
new_df.isnull().sum()

Country               427
City                    1
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
dtype: int64

In [16]:
new_df["City"]=new_df["City"].fillna("Unknown")

In [17]:
new_df.isnull().sum()

Country               427
City                    0
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
dtype: int64

In [18]:
new_df["Country"]=new_df["Country"].fillna("Unknown")

In [19]:
new_df.isnull().sum()

Country               0
City                  0
AQI Value             0
AQI Category          0
CO AQI Value          0
CO AQI Category       0
Ozone AQI Value       0
Ozone AQI Category    0
NO2 AQI Value         0
NO2 AQI Category      0
PM2.5 AQI Value       0
PM2.5 AQI Category    0
dtype: int64

In [22]:
countries=df["Country"].tolist()

In [25]:
countries

['Russian Federation',
 'Brazil',
 'Italy',
 'Poland',
 'France',
 'United States of America',
 'Germany',
 'Belgium',
 'Russian Federation',
 'Egypt',
 'China',
 'Netherlands',
 'India',
 'Pakistan',
 'Republic of North Macedonia',
 'France',
 'India',
 'Italy',
 'United States of America',
 'India',
 'Poland',
 'India',
 'Brazil',
 'China',
 'Brazil',
 'India',
 'Colombia',
 'Romania',
 'Russian Federation',
 'France',
 'United States of America',
 'Indonesia',
 'Brazil',
 'Finland',
 'South Africa',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'United States of America',
 'Brazil',
 'China',
 'Russian Federation',
 'United Republic of Tanzania',
 'India',
 'United States of America',
 'Belgium',
 'Egypt',
 'Haiti',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'Pakistan',
 'India',
 'Pakistan',
 'Somalia',
 'Philippines',
 'Latvia',
 'United States of America',
 'Netherlands',
 'United States of America',
 'United States of America',
 'Poland',
 'Colombia',
 'Italy',
 'Chad',
 'United Kingdom of Great Britain and Northern Ireland',
 'Philippines',
 'Russian Federation',
 'United States of America',
 'United States of America',
 'Germany',
 'Germany',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'Brazil',
 'India',
 'Germany',
 'China',
 'Germany',
 'United States of America',
 'India',
 'Germany',
 'France',
 'United States of America',
 'New Zealand',
 'Tunisia',
 'Viet Nam',
 'Iran (Islamic Republic of)',
 'Italy',
 'India',
 'Brazil',
 'Mexico',
 'Mexico',
 'Italy',
 'Viet Nam',
 'China',
 'Indonesia',
 'Romania',
 'Tunisia',
 'Philippines',
 'Japan',
 'Mexico',
 'Brazil',
 'Brazil',
 'Brazil',
 'Mexico',
 'El Salvador',
 'United Republic of Tanzania',
 'Russian Federation',
 'India',
 'Brazil',
 'India',
 'Bulgaria',
 'Poland',
 'Philippines',
 'Nigeria',
 'Finland',
 'Brazil',
 'Philippines',
 'Brazil',
 'Nigeria',
 'Mexico',
 'Brazil',
 'Brazil',
 'Brazil',
 'South Sudan',
 'Guatemala',
 'United States of America',
 'United States of America',
 'Ireland',
 'Turkey',
 'Viet Nam',
 'United States of America',
 'United States of America',
 'Russian Federation',
 'India',
 'India',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'China',
 'China',
 'China',
 'China',
 'Peru',
 'China',
 'Democratic Republic of the Congo',
 'China',
 'China',
 'China',
 'United States of America',
 'Germany',
 'United States of America',
 'Belgium',
 'Canada',
 'Ireland',
 'Switzerland',
 'Germany',
 'United States of America',
 'United States of America',
 'Brazil',
 'Denmark',
 'United States of America',
 'Germany',
 'Japan',
 'China',
 'United Kingdom of Great Britain and Northern Ireland',
 'Germany',
 'Germany',
 'Cameroon',
 'Somalia',
 'Netherlands',
 'Australia',
 'Germany',
 'Colombia',
 'Russian Federation',
 'United Kingdom of Great Britain and Northern Ireland',
 'Portugal',
 'Russian Federation',
 'India',
 "Côte d'Ivoire",
 'United States of America',
 'Sweden',
 'United States of America',
 'Germany',
 'China',
 'Ethiopia',
 'Nigeria',
 'Italy',
 'Germany',
 'Japan',
 'Thailand',
 'Indonesia',
 'Russian Federation',
 'Japan',
 'Poland',
 'Hungary',
 'Hungary',
 'Tunisia',
 'India',
 'Iran (Islamic Republic of)',
 'Philippines',
 'Japan',
 'Japan',
 'Japan',
 'India',
 'Philippines',
 'Russian Federation',
 'Kazakhstan',
 'United States of America',
 'Israel',
 'Japan',
 'Romania',
 'Philippines',
 'Indonesia',
 'Turkey',
 'India',
 'United Kingdom of Great Britain and Northern Ireland',
 'China',
 'China',
 'Poland',
 'Poland',
 'Belgium',
 'Belgium',
 'China',
 'China',
 'China',
 'China',
 'Mexico',
 'Mexico',
 'Russian Federation',
 'Netherlands',
 'Spain',
 'Italy',
 "Côte d'Ivoire",
 'Mexico',
 'United States of America',
 'United States of America',
 'India',
 'Nigeria',
 'France',
 'Myanmar',
 'United States of America',
 'Russian Federation',
 'Belgium',
 'Canada',
 'Brazil',
 'Spain',
 'Papua New Guinea',
 'Germany',
 'Madagascar',
 'China',
 'Madagascar',
 'United States of America',
 'Lithuania',
 'Ghana',
 'Mexico',
 'Brazil',
 'Russian Federation',
 'France',
 'Russian Federation',
 'Azerbaijan',
 'Armenia',
 'Ethiopia',
 'Iran (Islamic Republic of)',
 'India',
 'Guatemala',
 'Italy',
 'Ukraine',
 'Portugal',
 'Malaysia',
 'United Kingdom of Great Britain and Northern Ireland',
 'Netherlands',
 'Serbia',
 'Germany',
 'Pakistan',
 'South Africa',
 'South Africa',
 'Thailand',
 'Malaysia',
 'Philippines',
 'Slovakia',
 'Germany',
 'United States of America',
 'Gambia',
 'Pakistan',
 'Malaysia',
 'India',
 'Italy',
 'Italy',
 'Philippines',
 'Ecuador',
 'Bosnia and Herzegovina',
 'Italy',
 'Italy',
 'Czechia',
 'Argentina',
 'Peru',
 'France',
 'China',
 'Viet Nam',
 'Russian Federation',
 'Russian Federation',
 'India',
 'India',
 'Mexico',
 'India',
 'Poland',
 'India',
 'United States of America',
 'Brazil',
 'Brazil',
 'Brazil',
 'United Kingdom of Great Britain and Northern Ireland',
 'Ireland',
 'Brazil',
 'Romania',
 'Dominican Republic',
 'Italy',
 'Brazil',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'United States of America',
 'Brazil',
 'Argentina',
 'Mexico',
 'Italy',
 'Azerbaijan',
 'Spain',
 'India',
 'Brazil',
 'Germany',
 'United States of America',
 'Poland',
 'Guinea',
 'Pakistan',
 'France',
 'United States of America',
 'Ghana',
 'China',
 'Brazil',
 'Bolivia (Plurinational State of)',
 'Germany',
 'United States of America',
 'India',
 'United States of America',
 'Russian Federation',
 'Bangladesh',
 'Pakistan',
 'India',
 'India',
 'India',
 'Indonesia',
 'Brazil',
 'Russian Federation',
 'Sudan',
 'Colombia',
 'Philippines',
 'Iran (Islamic Republic of)',
 'India',
 'Thailand',
 'Thailand',
 'Netherlands',
 'United States of America',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'Serbia',
 'Netherlands',
 'Chile',
 'Panama',
 'Mexico',
 'United States of America',
 'United States of America',
 'Ghana',
 'Japan',
 'Germany',
 'Republic of North Macedonia',
 'Japan',
 'Poland',
 'Germany',
 'Brazil',
 'Japan',
 'Netherlands',
 'United States of America',
 'United States of America',
 'Poland',
 'Guatemala',
 'Congo',
 'Brazil',
 'Nigeria',
 'Kyrgyzstan',
 'Italy',
 'India',
 'Mauritius',
 'France',
 'India',
 'Philippines',
 'Indonesia',
 'China',
 'China',
 'China',
 'Brazil',
 'Brazil',
 'Peru',
 'United States of America',
 'United States of America',
 'United States of America',
 'Kazakhstan',
 'India',
 'United States of America',
 'Greece',
 'Mexico',
 'Serbia',
 'Thailand',
 'Thailand',
 'Thailand',
 'India',
 'Egypt',
 'Italy',
 'Russian Federation',
 'United Kingdom of Great Britain and Northern Ireland',
 'Germany',
 'Czechia',
 'Malawi',
 'Switzerland',
 'Brazil',
 'Serbia',
 'Cuba',
 'India',
 'United States of America',
 'United States of America',
 'Canada',
 'France',
 'Belgium',
 'France',
 'Saudi Arabia',
 'Japan',
 'United Kingdom of Great Britain and Northern Ireland',
 'India',
 'Brazil',
 'India',
 'Turkey',
 'Indonesia',
 'Brazil',
 'United States of America',
 'Canada',
 'Indonesia',
 'Peru',
 'Spain',
 'Mexico',
 'Israel',
 'Chile',
 'India',
 'United States of America',
 'Bangladesh',
 'India',
 'Thailand',
 'India',
 'Brazil',
 'Finland',
 'Germany',
 'United States of America',
 'Benin',
 'Italy',
 'Sierra Leone',
 'Haiti',
 'Portugal',
 'United States of America',
 'United States of America',
 'India',
 'Thailand',
 'Germany',
 'Russian Federation',
 'Brazil',
 'Brazil',
 'United States of America',
 'United States of America',
 'Brazil',
 'Peru',
 'France',
 'Lebanon',
 'Italy',
 'France',
 'Brazil',
 'France',
 'Philippines',
 'India',
 'United States of America',
 'India',
 'Thailand',
 'China',
 'India',
 'United Republic of Tanzania',
 'India',
 'Brazil',
 'Uruguay',
 'India',
 'Russian Federation',
 'Turkey',
 'India',
 'Turkey',
 'Ukraine',
 'Benin',
 'Russian Federation',
 'United States of America',
 'United Republic of Tanzania',
 'United States of America',
 'United States of America',
 'Mexico',
 'United States of America',
 'Mexico',
 'Bolivia (Plurinational State of)',
 'United States of America',
 'Pakistan',
 'Japan',
 'Italy',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Kingdom of Great Britain and Northern Ireland',
 'Namibia',
 'India',
 'India',
 'Spain',
 'India',
 'India',
 'Brazil',
 'Netherlands',
 'United States of America',
 'Poland',
 'Iran (Islamic Republic of)',
 'Russian Federation',
 'Japan',
 'Albania',
 'United States of America',
 'United States of America',
 'Mexico',
 'Germany',
 'Cameroon',
 'China',
 'France',
 'United States of America',
 'France',
 'United States of America',
 'United States of America',
 'Brazil',
 'Germany',
 'United States of America',
 'Japan',
 'Germany',
 'Israel',
 'India',
 'Spain',
 'Italy',
 'Netherlands',
 'Germany',
 'Guyana',
 'Germany',
 'India',
 'United States of America',
 'United States of America',
 'Thailand',
 'Philippines',
 'Iran (Islamic Republic of)',
 'Brazil',
 'China',
 'India',
 'Germany',
 'France',
 'Brazil',
 'Colombia',
 'Netherlands',
 'United Kingdom of Great Britain and Northern Ireland',
 'Philippines',
 'France',
 'Germany',
 'Malaysia',
 'China',
 'Czechia',
 'Belgium',
 'Belgium',
 'Netherlands',
 'Congo',
 'Senegal',
 'Poland',
 'Poland',
 'Indonesia',
 'Philippines',
 'India',
 'Ukraine',
 'Brazil',
 'Pakistan',
 'Lesotho',
 'United States of America',
 'United Republic of Tanzania',
 'India',
 'India',
 'India',
 'India',
 'United States of America',
 'Ukraine',
 'France',
 'Philippines',
 'Benin',
 'Iran (Islamic Republic of)',
 'Italy',
 'Mongolia',
 'India',
 'Democratic Republic of the Congo',
 'Venezuela (Bolivarian Republic of)',
 'Italy',
 'India',
 'Germany',
 'China',
 'France',
 'Germany',
 'United States of America',
 'Japan',
 'India',
 'Bulgaria',
 'Pakistan',
 'Germany',
 'United States of America',
 'United States of America',
 'Finland',
 'Japan',
 'Germany',
 'China',
 'Japan',
 'Japan',
 'United States of America',
 'Somalia',
 'Japan',
 'Solomon Islands',
 'India',
 'Paraguay',
 'Armenia',
 'China',
 'Peru',
 'Zimbabwe',
 'Japan',
 'India',
 'Nigeria',
 'India',
 'India',
 'Russian Federation',
 'India',
 'Namibia',
 'Ukraine',
 'United Republic of Tanzania',
 'Turkey',
 'Ukraine',
 'United States of America',
 'Russian Federation',
 'Austria',
 'Croatia',
 'Papua New Guinea',
 'Russian Federation',
 'Czechia',
 'Poland',
 'Russian Federation',
 'Poland',
 'Pakistan',
 'Russian Federation',
 'India',
 'Chad',
 'India',
 'Ukraine',
 'Russian Federation',
 'Russian Federation',
 'Germany',
 'Germany',
 'Ukraine',
 'India',
 'Russian Federation',
 'India',
 'Japan',
 'Myanmar',
 'Mexico',
 'France',
 'Honduras',
 'United States of America',
 'Brazil',
 'Brazil',
 'Germany',
 'Brazil',
 'Brazil',
 'Japan',
 'Spain',
 'India',
 'India',
 'Nigeria',
 'United Kingdom of Great Britain and Northern Ireland',
 'Japan',
 "Côte d'Ivoire",
 'Brazil',
 'Brazil',
 'Ukraine',
 'Ukraine',
 'Spain',
 'India',
 'India',
 'India',
 'India',
 'China',
 'Mexico',
 'India',
 'China',
 'Poland',
 'Germany',
 'United Republic of Tanzania',
 'China',
 'Finland',
 'India',
 'India',
 'Russian Federation',
 'Ukraine',
 'Cambodia',
 'Pakistan',
 'India',
 'Finland',
 'China',
 'India',
 'India',
 'India',
 'India',
 'Russian Federation',
 'Japan',
 'United States of America',
 'Hungary',
 'Belgium',
 'Turkey',
 'United States of America',
 'United States of America',
 'India',
 'India',
 'Italy',
 'France',
 'United States of America',
 'Uganda',
 'Malaysia',
 'Chad',
 'United Republic of Tanzania',
 'Tunisia',
 'Germany',
 'Philippines',
 'Cuba',
 'Senegal',
 'Colombia',
 'Argentina',
 'United States of America',
 'United States of America',
 'Hungary',
 'Netherlands',
 'Turkey',
 'Brazil',
 'Uruguay',
 'Brazil',
 'India',
 'India',
 'Italy',
 'Indonesia',
 'Japan',
 'Philippines',
 'France',
 'France',
 'Hungary',
 'Bangladesh',
 'Belgium',
 'United States of America',
 'India',
 'Italy',
 'Germany',
 'Mexico',
 'Poland',
 'India',
 'India',
 'Mexico',
 'India',
 'Italy',
 'Pakistan',
 'India',
 'India',
 'Romania',
 'Germany',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Kingdom of Great Britain and Northern Ireland',
 'Republic of Moldova',
 'Japan',
 'Russian Federation',
 'Germany',
 'India',
 'India',
 'India',
 'India',
 'Thailand',
 'Sudan',
 'United States of America',
 'India',
 'India',
 'Hungary',
 'United States of America',
 'India',
 'Pakistan',
 'South Africa',
 'China',
 'Russian Federation',
 'Ukraine',
 'Guinea',
 'Bulgaria',
 'United States of America',
 'Italy',
 'Bolivia (Plurinational State of)',
 'United States of America',
 'India',
 'Finland',
 'Myanmar',
 'Italy',
 'Russian Federation',
 'Chile',
 'Angola',
 'Germany',
 'Democratic Republic of the Congo',
 'India',
 'Belgium',
 'Colombia',
 'India',
 'India',
 'Turkey',
 'Turkey',
 'Philippines',
 'India',
 'Philippines',
 'India',
 'Kingdom of Eswatini',
 'Ukraine',
 'Afghanistan',
 'India',
 'Switzerland',
 'Peru',
 'Spain',
 'Spain',
 'Mexico',
 'Spain',
 'United States of America',
 'Malaysia',
 'India',
 'India',
 'Indonesia',
 'Belgium',
 'France',
 'Italy',
 'Mexico',
 'Italy',
 'France',
 'France',
 'Portugal',
 'Belgium',
 'Italy',
 'United States of America',
 'Mexico',
 'Bulgaria',
 'China',
 'United States of America',
 'Malawi',
 'Pakistan',
 'Nigeria',
 'India',
 'Russian Federation',
 'India',
 'Indonesia',
 'India',
 'India',
 'India',
 'United States of America',
 'India',
 'Uzbekistan',
 'Indonesia',
 'Finland',
 'Poland',
 'France',
 'Sweden',
 'Germany',
 'Peru',
 'Brazil',
 'Tunisia',
 'China',
 'Zambia',
 'United States of America',
 'Morocco',
 'India',
 'Ireland',
 'Pakistan',
 'Ghana',
 'Japan',
 'Spain',
 'India',
 'United States of America',
 'India',
 'Netherlands',
 'Russian Federation',
 'India',
 'China',
 'Hungary',
 'France',
 'Pakistan',
 'India',
 'India',
 'Pakistan',
 'India',
 'Thailand',
 'France',
 'United States of America',
 'Ukraine',
 'United States of America',
 'Slovakia',
 'New Zealand',
 'Brazil',
 'Germany',
 'Sweden',
 'Italy',
 'United States of America',
 'Pakistan',
 'Germany',
 'Portugal',
 'Mexico',
 'China',
 'China',
 'Angola',
 'Philippines',
 'Belarus',
 'Russian Federation',
 'Netherlands',
 'Guinea',
 'United States of America',
 'Pakistan',
 'Germany',
 'Indonesia',
 'Philippines',
 'United Republic of Tanzania',
 'India',
 'Philippines',
 'Italy',
 'India',
 'Spain',
 'Philippines',
 'Russian Federation',
 'Russian Federation',
 'Russian Federation',
 'Russian Federation',
 'Netherlands',
 'Norway',
 'Thailand',
 'Pakistan',
 'Germany',
 'India',
 'Russian Federation',
 'Indonesia',
 'Belgium',
 'France',
 'France',
 'Mexico',
 'Nigeria',
 'Portugal',
 'Russian Federation',
 'Morocco',
 'Iran (Islamic Republic of)',
 'Azerbaijan',
 'Pakistan',
 'Indonesia',
 'Egypt',
 'China',
 'United States of America',
 'India',
 'Brazil',
 'Guatemala',
 'Italy',
 'Indonesia',
 'China',
 'India',
 'Germany',
 'Indonesia',
 'United Kingdom of Great Britain and Northern Ireland',
 'India',
 'Hungary',
 'Hungary',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'Ecuador',
 'Venezuela (Bolivarian Republic of)',
 'Spain',
 'Guatemala',
 'Spain',
 'United States of America',
 'Germany',
 'Brazil',
 'India',
 'United States of America',
 'Iran (Islamic Republic of)',
 ...]

In [26]:
high_salary=df[df["AQI Value"]>50][["Country","City"]]

In [27]:
high_salary

                        Country              City
0            Russian Federation        Praskoveya
2                         Italy   Priolo Gargallo
5      United States of America       Punta Gorda
6                       Germany        Puttlingen
7                       Belgium             Puurs
...                         ...               ...
23456  United States of America  Highland Springs
23457                  Slovakia            Martin
23458                     India      Gursahaiganj
23461  United States of America       Westerville
23462                  Malaysia            Marang

[13348 rows x 2 columns]